### ISSUE TITLE
Long term TODO list

### ISSUE THREAD

**Issue by tchock** [Bojagi/pablo#26]
Concepts:
- [x] breakpoints
- [x] Mobile/Desktop show/hide components
- [ ] elevation (Box)
- [x] Grid

Components:
- [ ] Select
- [ ] Searchable select
- [ ] Autosuggest
- [x] Slider
- [ ] Table
- [ ] Tags
- [ ] Alert
- [ ] Badge
- [ ] Tag dropdown/select
- [ ] Checkbox Group (with label)
- [ ] Label for `RadioGroup`
- [ ] Switch group
- [ ] Standalone `Label`
- [ ] Breadcrumb
- [ ] Pagination
